### ISSUE TITLE
Separate bots by team in batch.yaml

### ISSUE THREAD

**Issue by peter-drew** [MelbourneHighSchoolRobotics/ev3sim#135]
For example
```
preset_file: soccer.yaml
team1-bots:
- name: templateBot.yaml
  scripts:
  - templateBot.py
team2-bots:
- name: templateBot.yaml
  scripts:
  - templateBot.py
```

Would need to maintain backwards compatibility.
